### ISSUE TITLE
Release checklist 0.1.0-beta2

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/oxide.go#170]
- [x] Make sure version is set to 0.1.0-beta2 in VERSION file https://github.com/oxidecomputer/oxide.go/pull/171
- [x] Generate changelog https://github.com/oxidecomputer/oxide.go/pull/172
- [x] Release the new version https://pkg.go.dev/github.com/oxidecomputer/oxide.go@v0.1.0-beta2
